#!/bin/sh

# Cleanup previous builds
rm -rf obj_dir
rm -f CUSE.vcd

# Run Verilator to translate Verilog files into C++, including C++ testbench
verilator -Wall --cc --trace CUSE.sv ControlUnit.sv SignExtender.sv --exe CUSE_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VCUSE.mk VCUSE

# Run executable simulation file
obj_dir/VCUSE
